name: Installation Tests

on:
    release:
      types: [published]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: print tag
        run: |
            echo "New tag: ${{ github.event.release.tag_name }}"
      - name: test brew
        run: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew -v