name: Installation Tests

on:
    release:
      types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Print Tag
        run: |
            echo "New tag: ${{ github.event.release.tag_name }}"
      - name: test kaytu
        run: |
            curl -fsSL https://raw.githubusercontent.com/kaytu-io/kaytu/main/scripts/install.sh | sh
            kaytu version
  darwin:
    runs-on: macos-latest
    steps:
      - name: Avoiding Rate Limiting
        run: sleep 2
      - name: Tap Kaytu's cli-tap
        run: brew tap kaytu-io/cli-tap 
      - name: Install Kaytu 
        run: brew install kaytu
      - name: Check Kaytu Version
        run: kaytu version
       