name: Release

on:
  push:
    tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+'  
      - 'v[0-9]+.[0-9]+.[0-9]+-rc'
  workflow_dispatch:
    inputs:
      publishChocolatey:
        type: choice
        description: "Publish to chocolatey"
        options:
          - "true"
          - "false"
        default: "false"

env:
    REPOSITORY_OWNER: "adorigi"
    REPOSITORY_NAME: "kaytu"
    HOMEBREW_TAP: "homebrew-adorigi"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install cosign
        run: |
          curl -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64"
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign
          sudo chmod +x /usr/local/bin/cosign
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}
          COSIGN_SECRET: ${{ secrets.COSIGN_SECRET }}
          REPOSITORY_OWNER: ${{ env.REPOSITORY_OWNER }}
          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}
          HOMEBREW_TAP: ${{ env.HOMEBREW_TAP }}

  sign-windows:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Set new tag
        id: set_new_tag
        run: |
            export VERSION=${{ github.ref_name }}
            export VERSION=${VERSION#v}
            echo "version=$VERSION"
            echo "::set-output name=new_tag::$VERSION"
      - uses: robinraju/release-downloader@v1.10
        id: download_release_amd64
        with:
          repository: "kaytu-io/kaytu"
          fileName: '*'
          latest: true
      - name: Add windows zip
        id: add_windows_zip
        run: |
          export VERSION=${{ github.ref_name }}
          export VERSION=${VERSION#v}
          echo "version=$VERSION"
          echo "kaytu_$VERSION_darwin_amd64"

          sudo apt update -y && sudo apt -y install cmake libssl-dev libcurl4-openssl-dev zlib1g-dev python3
          sudo apt-get update -y
          sudo apt-get -y install osslsigncode
          echo "${{ secrets.SELFSIGNED_KEY }}" | base64 --decode > cert.key
          echo "${{ secrets.SELFSIGNED_CRT }}" | base64 --decode > cert.crt          
          osslsigncode sign -certs cert.crt -key cert.key -n "Kaytu" -i https://kaytu.io/ -in kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64.exe -out kaytu.exe
          mkdir kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64
          mv kaytu.exe kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64
          zip -r kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64.zip kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64
          sha256sum kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64.zip > kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64_checksum.txt
          
          sed -i '/kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64.zip/{
            r kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64_checksum.txt
            d
          }' kaytu_${{ steps.set_new_tag.outputs.new_tag }}_checksums.txt
          
          export UPLOAD_URL=$(curl --silent "https://api.github.com/repos/kaytu-io/kaytu/releases/latest" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"  | jq -r .upload_url)
          echo "$UPLOAD_URL"
          echo "upload_url=$UPLOAD_URL" >> $GITHUB_OUTPUT

          release_id=$(curl --request GET \
            --url https://api.github.com/repos/kaytu-io/kaytu/releases/latest \
            --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}' | jq '.id')
          echo $release_id
          assets=$(curl --request GET \
            --url https://api.github.com/repos/kaytu-io/kaytu/releases/$release_id/assets \
            --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}')
          echo $assets
          amd64=$(echo $assets | jq '.[] | select(.name=="kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64.exe") | .id')
          curl --request DELETE \
            --url https://api.github.com/repos/kaytu-io/kaytu/releases/assets/$amd64 \
            --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}'
          linuxarm64=$(echo $assets | jq '.[] | select(.name=="kaytu_${{ steps.set_new_tag.outputs.new_tag }}_linux_arm64") | .id')
          curl --request DELETE \
            --url https://api.github.com/repos/kaytu-io/kaytu/releases/assets/$linuxarm64 \
            --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}'
          linuxamd64=$(echo $assets | jq '.[] | select(.name=="kaytu_${{ steps.set_new_tag.outputs.new_tag }}_linux_amd64") | .id')
          curl --request DELETE \
            --url https://api.github.com/repos/kaytu-io/kaytu/releases/assets/$linuxamd64 \
            --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}'
          darwinarm64=$(echo $assets | jq '.[] | select(.name=="kaytu_${{ steps.set_new_tag.outputs.new_tag }}_darwin_arm64") | .id')
          curl --request DELETE \
            --url https://api.github.com/repos/kaytu-io/kaytu/releases/assets/$darwinarm64 \
            --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}'
          darwinamd64=$(echo $assets | jq '.[] | select(.name=="kaytu_${{ steps.set_new_tag.outputs.new_tag }}_darwin_amd64") | .id')
          curl --request DELETE \
            --url https://api.github.com/repos/kaytu-io/kaytu/releases/assets/$darwinamd64 \
            --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}'
          windowszip=$(echo $assets | jq '.[] | select(.name=="kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64.zip") | .id')
          curl --request DELETE \
            --url https://api.github.com/repos/kaytu-io/kaytu/releases/assets/$windowszip \
            --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}'
          windowschecksum=$(echo $assets | jq '.[] | select(.name=="kaytu_${{ steps.set_new_tag.outputs.new_tag }}_checksums.txt") | .id')
          curl --request DELETE \
            --url https://api.github.com/repos/kaytu-io/kaytu/releases/assets/$windowschecksum \
            --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}'

      - name: Upload Release Asset amd64 zip
        id: upload-release-asset-amd64-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.add_windows_zip.outputs.upload_url }}
          asset_path: ./kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64.zip
          asset_name: kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64.zip
          asset_content_type: application/zip
      - name: Upload Release Asset amd64 zip checksum
        id: upload-release-asset-amd64-zip-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.add_windows_zip.outputs.upload_url }}
          asset_path: ./kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64_checksum.txt
          asset_name: kaytu_${{ steps.set_new_tag.outputs.new_tag }}_windows_amd64_checksum.txt
          asset_content_type: text/plain
      - name: Upload Release Asset new checksum
        id: upload-release-asset-new-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.add_windows_zip.outputs.upload_url }}
          asset_path: ./kaytu_${{ steps.set_new_tag.outputs.new_tag }}_checksums.txt
          asset_name: kaytu_${{ steps.set_new_tag.outputs.new_tag }}_checksums.txt
          asset_content_type: text/plain
  chocolatey-publish:
    name: Release Kaytu choco
    if: github.event.inputs.publishChocolatey == 'true'
    runs-on: windows-latest
    needs:
      - release
      - sign-windows
    steps:
      - uses: actions/checkout@v2
      - name: Generate & push
        run: scripts/build.ps1
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_APIKEY }}