name: Pre-Release

on:
  push:
    tags:        
    - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]{1,2}' 
  workflow_dispatch:
jobs:
    tag:
        runs-on: ubuntu-latest
        outputs:
          latest_tag: ${{ steps.set_latest_tag.outputs.latest_tag }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
              token: ${{ secrets.GITHUB_TOKEN }}
          - name: Tag version
            id: tag_version
            uses: mathieudutour/github-tag-action@v6.1
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              pre_release_branches: nightly-builds 
              append_to_pre_release_tag: rc
              tag_prefix: v
          - name: Set latest tag output
            id: set_latest_tag
            run: |
              if [[ -z "${{ steps.tag_version.outputs.new_tag }}" ]]; then
                echo "latest_tag=${{ steps.tag_version.outputs.previous_tag }}" >> "$GITHUB_OUTPUT"
              else
                echo "latest_tag=${{ steps.tag_version.outputs.new_tag }}" >> "$GITHUB_OUTPUT"
              fi
          - name: Save new tag
            id: save_new_tag
            run: |
              version=${{ steps.tag_version.outputs.new_tag }}
              version=${version#v}
              echo $version > new_tag.txt
          - name: Upload new tag
            uses: actions/upload-artifact@v2
            with:
              name: new_tag
              path: new_tag.txt